# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
before_install:
 - gem install cocoapods
 - pod install --project-directory=Example
script:
- xctool test -workspace Example/RxRealm.xcworkspace -scheme RxRealm-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
